### ISSUE TITLE
Missing dependency to imported proto files

### ISSUE THREAD

**Issue by gajarskymartin** [bjorkstromm/dotnet-grpc-cli#1]
"ls" command on service which contains imported proto file ends with error:
Error: Dependency missing: Protos/imported.proto

**Comment by Edward-Alchikha** [comment]
Any progress on or workarounds for this? This stops it from working on any protos using any of the WellKnownTypes (in my case Timestamp)

The exception is thrown by Google.Protobuf.Reflection.FileDescriptor.BuildFromByteStrings(IEnumerable`1 descriptorData)

**Comment by bjorkstromm** [comment]
@Edward-Alchikha Initially this was an issue when using protobuf-net.Grpc... But now I'm unsure. Do you happen to have some minimal steps to reproduce. Also, what server are you using?

**Comment by codecooper** [comment]
I am having the same issue as well. I am using .NET6 and serving and using `Grpc.AspNetCore.Server.Reflection` to serve up the protobufs.  In my proto I am importing via:
`import` "google/protobuf/timestamp.proto";`
I am using the `dotnet grpc-cli` utility to dump the files from reflection. The following command works for any proto that does use the WellKnownTypes from google.
`dotnet grpc-cli dump localhost:6504 SampleService -o Protos`

If the proto does contain timestamp.proto then I get the following error: `Error: Dependency missing: google/protobuf/timestamp.proto`

**Comment by bjorkstromm** [comment]
@codecooper do you happen to have a repro to share? I just tried this out, and unfortunately I'm unable to reproduce.

Here's what I did:

1. Create a new gRPC Server project (`dotnet new grpc`).
2. Add `Grpc.AspNetCore.Server.Reflection` package (version 2.45.0), and update `Grpc.AspNetCore` to latest (version 2.45.0).
```csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Protos\greet.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.45.0" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.45.0" />
  </ItemGroup>

</Project>
```
3. Modify protos/greet.proto to use a well-known type.
```proto
syntax = "proto3";

import "google/protobuf/timestamp.proto";

option csharp_namespace = "proto_test";

package greet;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply);
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
  google.protobuf.Timestamp ts = 2;
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
  google.protobuf.Timestamp ts = 2;
}

```
4. Register gRPC Server reflection in `Program.cs`
```csharp
using proto_test.Services;

var builder = WebApplication.CreateBuilder(args);

// Additional configuration is required to successfully run gRPC on macOS.
// For instructions on how to configure Kestrel and gRPC clients on macOS, visit https://go.microsoft.com/fwlink/?linkid=2099682

// Add services to the container.
builder.Services.AddGrpc();
builder.Services.AddGrpcReflection();

var app = builder.Build();

// Configure the HTTP request pipeline.
app.MapGrpcService<GreeterService>();
app.MapGrpcReflectionService();
app.MapGet("/", () => "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");

app.Run();
```
5. Start server
```dotnet-cli
dotnet run
```
6. From another console, run `grpc-cli` (server is listening on https://localhost:7078 in my case)
```dotnet-cli
dotnet grpc-cli dump https://localhost:7078 greet.Greeter
```
The above successfully dumped this to the console.
```
---
File: Protos/greet.proto
---
syntax = "proto3";
import "google/protobuf/timestamp.proto";
package greet;

message HelloRequest {
  string name = 1;
  google.protobuf.Timestamp ts = 2;
}

message HelloReply {
  string message = 1;
  google.protobuf.Timestamp ts = 2;
}

service Greeter {
   rpc SayHello(greet.HelloRequest) returns (greet.HelloReply);
}
```

**Comment by codecooper** [comment]
Thank you for the hand-holding. Sometimes, you need someone else to tell you to slow down and try building from scratch. This helped. You are correct, this does work. After playing around with what you detailed above I think I have found the real problem. I have 20+ proto files with ~50 methods total. They all use the same message as a request model. To do this, they all import a common proto file. This common file references `import "google/protobuf/timestamp.proto";` as well.
```
//greet.proto
syntax = "proto3";
import "google/protobuf/timestamp.proto";
import "Protos/common.proto";

option csharp_namespace = "deleteme";

package greet;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply);
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
  google.protobuf.Timestamp ts = 2;
}
```
```
// common.proto
syntax = "proto3";
import "google/protobuf/timestamp.proto";

option csharp_namespace = "deleteme";

package greet;

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
  google.protobuf.Timestamp ts = 2;
}
```
It seems that the issue the nesting of imports. I know grpcui can work with this. But I am not good enough at go. I may just have to re-structure my files and requests.

**Comment by bjorkstromm** [comment]
@codecooper thanks for the investigation! I'm now able to reproduce, and hopefully provide a fix. Altough I'd argue issue with [Grpc.Reflection](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Reflection/ReflectionServiceImpl.cs) not sorting transitive dependencies correctly. We had similar issue with [Protobbuf-net.Grpc](https://github.com/protobuf-net/protobuf-net.Grpc/pull/153) which we fixed.

Unfortunately the [reflection docs](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md) doesn't really say much about the order of dependencies. But I know that this method here, requires the dependencies to be correctly ordered.
https://github.com/bjorkstromm/dotnet-grpc-cli/blob/bedea1d61228afb797cc83fe95f96ccb068b6a1b/grpc.cli/DumpCommand.cs#L31

**Comment by bjorkstromm** [comment]
@codecooper v0.6.0 is pushed to NuGet, and will soon be available. Thanks again for the repro!
https://www.nuget.org/packages/dotnet-grpc-cli/0.6.0
